name: CI
on: [push]
jobs:
  build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Example
        working-directory: ./example
        run: npm i

      - name: Run Tests
        working-directory: ./example
        run: npm run test:ci
          
      - name: Install Dependencies
        working-directory: ./
        run: npm i
          
      - name: Build Library
        working-directory: ./exampe
        run: npm run build
